### 获取验证码
GET  http://localhost:3000/api/public/captcha HTTP/1.1

### 注册
POST http://localhost:3000/api/register HTTP/1.1
Content-Type: application/json

{
"username":"1392830517@qq.com",
"nickname":"wangliang",
"password":"Wl123456",
"confirmPassword":"Wl123456",
"code":"xu5x",
"sid":"cfcf724f-3519-429b-895b-0880af13e918"
}

# {
#     "email": "1392830517@qq.com",
#     "username": "wangliang",
#     "password": "Wl123456",
#     "nickname": "汤杰",
#     "created": "2024-08-10 08:04:06",
#     "updated": "2024-08-10 08:04:06",
#     "favs": 41,
#     "gender": "1",
#     "roles": "super_admin",
#     "avatar": "http://dummyimage.com/100x100",
#     "phone": "13041700015",
#     "status": "0",
#     "regmark": "若暗夜终临，吾将立于万万人之前，横刀向渊",
#     "location": "香港特别行政区 香港岛",
#     "vip": "2",
#     "count": 42
# }




### post
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "11@qq.com",
    "password": "test11",
    "code": "1234"
}

### put
PUT http://localhost:3000/api/user/123 HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "age": 14,
    "gender": "male",
    "email": "test@test.com",
    "password": "test"
}


### 请求静态资源
GET http://localhost:3000/1.png HTTP/1.1


