### 获取验证码
GET  http://localhost:3000/api/captcha HTTP/1.1

### get
GET http://localhost:3000/api/user HTTP/1.1



### post
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "password": "test1",
    "code": "1234"
}

### put
PUT http://localhost:3000/api/user/123 HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "age": 14,
    "gender": "male",
    "email": "test@test.com",
    "password": "test"
}


### 请求静态资源
GET http://localhost:3000/1.png HTTP/1.1


