# frpc.toml 配置文件

# 公网服务器地址
[common]
server_addr = "101.37.12.36"
server_port = 7500

# 身份验证令牌
token = "1234567890"

# GitLab 代理配置
[[proxies]]
name = "web"
type = "tcp"
remote_port = 13800 # 这里是你希望外网访问的端口
local_ip = "127.0.0.1"
local_port = 5501 # 这里是本地 GitLab 的端口



