version: '3'

services:
  gitlab_test:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab_test
    hostname: 127.0.0.1 # 这里用实际域名或IP，这里保持与external_url一致
    environment:
      - GITLAB_OMNIBUS_CONFIG="external_url 'http://127.0.0.1:13800';"
    ports:
      - "13800:80"
      - "13822:22"
    volumes:
      - d:/dockerData/gitlab/config:/etc/gitlab
      - d:/dockerData/gitlab/logs:/var/log/gitlab
      - d:/dockerData/gitlab/data:/var/opt/gitlab
    restart: always