version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /app/mongo/data:/data/db
    ports:
      - 27017:27017
