# frpc.toml 配置文件

# frpc.toml
serverPort = 7500           # [必选] 要连接的 frps 端口
serverAddr = "101.37.12.36" # [必选] 要连接的 frps 地址
log.to = "console"          # [可选] 日志配置, 通过打印的方式输出日志
auth.token = "1234567890"   # [可选] token 设置, frps 设置的 token, 其实就是密码

[[proxies]]
name = "web - tcp"        # 代理名称(随便填)
type = "tcp"              # 代理类型
localIP = "192.168.100.136" # 代理地址, 要转发到哪个地址
localPort = 13800          # 代理端口, 要转发到哪个端口
remotePort = 7001  
       # 远程端口(和远程 frps 哪个端口绑定在一起, 访问对应端口将使用该代理)



# 使用docker cp 将frpc.toml 文件拷贝到 /etc/frp/frpc.toml 目录下 启动 frpc 服务
# docker run -d --name frpc -v e:/dockerData/frp/frpc.toml:/etc/frp/frpc.toml --network=host  --restart=always snowdreamtech/frpc
# docker cp frpc.toml frpc:/etc/frp/frpc.toml

[[proxies]]
name = "web-html"                # 代理名称(随便填)
type = "http"                    # 代理类型
localIP = "192.168.100.136"        # 代理地址, 要转发到哪个地址
localPort = 13800
customDomains = ["101.37.12.36"]
